baseURL = 'https://org.rymcg.tech'
languageCode = 'en-us'
title = "org.rymcg.tech"
theme = "relearn"
publishDir = "../public"

[markup.goldmark.renderer]
  unsafe = true

[params]
  themeVariant = [
	{ identifier = "zen-auto",      name = "Zen Light/Dark", auto = [ "zen-light", "zen-dark" ] },
	{ identifier = "zen-light"      },
	{ identifier = "zen-dark"       },
	{ identifier = "relearn-auto",  name = "Relearn Light/Dark", auto = [] },
	{ identifier = "relearn-light"  },
	{ identifier = "relearn-dark"   },
	{ identifier = "relearn-bright" },
	{ identifier = "neon"           },
	{ identifier = "learn"          },
	{ identifier = "blue"           },
	{ identifier = "green"          },
	{ identifier = "red"            }
  ]

[outputs]
  home = ["HTML", "RSS", "SEARCH", "SEARCHPAGE"]
