baseURL = 'https://book.rymcg.tech'
languageCode = 'en-us'
title = "book.rymcg.tech"
theme = "terminal"
publishDir = "../public"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML", "RSS"]
