#+hugo_base_dir: ./hugo
#+hugo_section: /
#+hugo_weight: auto
#+hugo_paired_shortcodes: %notice badge button

* book.rymcg.tech
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
This repository contains a collection of books written by EnigmaCurry.

This content is open-source, CC BY 4.0. See [[file:~/git/vendor/enigmacurry/license.org][LICENSE]] for attribution rules.

** Table of contents

The website's left side menu bar contains the index of all the books,
with the title of the books as top level headings, and each chapter
heading beneath those. On smaller screens, you may need to expand this
menu using the top left hamburger menu.

At the top left of every page (and just to the right of the sidebar),
there is a button to show the current page outline. Many longer
chapters will have their own indexes listed at the top of their
respective page.

** Navigation

The entire site is presented as a book of books, so you can read
through them all, simply by navigating through to the next page, until
you get to the end. Use your keyboard arrow keys, left and right, to
flip backwards and forwards through the pages. If you are using a
touch screen interface, use the arrow buttons at the top right of the
page instead.

** Search

Use the search box in the left hand menu to search all of the books on
the site.

* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
