#+hugo_base_dir: ./hugo
#+hugo_section: /
#+hugo_weight: auto

* book.rymcg.tech
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
This repository contains a collection of books written by EnigmaCurry.

This content is open-source, CC BY 4.0. See [[file:~/git/vendor/enigmacurry/license.org][LICENSE]] for attribution rules.

** Table of contents

In HTML form, the menu bar on the left contains the table of contents,
and shows the book titles as top level headings, and chapter headings
beneath it. On smaller screens, you may need to expand this menu using
the top left hamburger menu.

When viewing any chapter, the section sub-headings can be shown on a
per-chapter basis, via the Table of Contents button at the top left.

** Navigation

The entire site is presented as a book of books, so you can read
through them all, simply by navigating through to the next page, until
you get to the end. Use your keyboard arrow keys, left and right, to
flip backwards and forwards through the pages. If you are using a
touch screen interface, use the arrow buttons at the top right of the
page instead.

** Search

Use the search box in the left hand menu to search all of the books on
the site.

* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
