#+hugo_base_dir: ./hugo
#+hugo_section: /
#+hugo_weight: auto
#+hugo_paired_shortcodes: %notice %annotate badge button %children %index run stdout edit math mermaid openapi toc env

* book.rymcg.tech
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:

#+attr_shortcode: :style info
#+begin_notice
This repository contains a collection of books written by EnigmaCurry.

This content is open-source, CC BY 4.0. See [[file:~/git/vendor/enigmacurry/license.org][LICENSE]] for attribution rules.
#+end_notice

** Books

#+attr_shortcode: :title false
#+begin_index
index
#+end_index

** Site features
*** Navigation

This website is presented as a book of books, so you can read
everything from beginning to end. There are two ways to flip through
the pages:

 * Press the keyboard *left* and *right* arrow keys.
 * Click the arrow buttons in the top right corner of every page
   (handy on a touch screen).

#+attr_shortcode: :title Keyboard navigation
#+begin_notice
#+begin_export html
<div class="uidemo">
<figure><span class="kbd">&#8592;</span><figcaption>previous page</figcaption></figure>
<figure><span class="kbd">&#8594;</span><figcaption>next page</figcaption></figure>
</div>
#+end_export
#+end_notice

#+attr_shortcode: :title Page-turn buttons
#+begin_notice
#+begin_export html
<div class="uidemo">
<figure><span class="navbtn navprev"></span><figcaption>previous page</figcaption></figure>
<figure><span class="navbtn toc-toggle"></span><figcaption>outline of this page</figcaption></figure>
<figure><span class="navbtn navnext"></span><figcaption>next page</figcaption></figure>
</div>
#+end_export
#+end_notice
*** Table of contents

The menu on the left lists every book on the site, with the book
titles as the top level headings. On smaller screens the menu is
hidden; tap the circle button in the top left corner to slide it open.

#+attr_shortcode: :title Menu button (small screens only)
#+begin_notice
#+begin_export html
<div class="uidemo">
<figure><span class="navbtn menudemo"></span><figcaption>show / hide the menu</figcaption></figure>
</div>
#+end_export
#+end_notice

Every page also has its own outline. Click the =#= button in the top
right corner to jump between the headings of the page you are reading.

#+attr_shortcode: :title Page outline
#+begin_notice
#+begin_export html
<div class="uidemo">
<figure><span class="navbtn toc-toggle"></span><figcaption>headings on this page</figcaption></figure>
</div>
#+end_export
#+end_notice

*** Theme
This website has a custom =terminal= theme with four colour palettes:
=amber=, =green=, =mono=, and =lite=. By default it follows your
operating system's light or dark mode preference (=lite= for light,
=green= for dark). You can switch palettes — and toggle the terminal
effects — from the controls in the lower left menu, below the table of
contents.

#+attr_shortcode: :title Change theme
#+begin_notice
#+begin_export html
<div class="uidemo">
<figure><span class="row"><span class="ctl-label">theme:</span><button class="btn" type="button">amber</button></span><figcaption>cycle the colour palette</figcaption></figure>
<figure><span class="row"><span class="ctl-label">fx:</span><button class="btn" type="button">on</button></span><figcaption>toggle terminal effects</figcaption></figure>
</div>
#+end_export
#+end_notice
*** Blocks
**** Shell command blocks

Throughout these books, you will find literal command blocks that you
should copy and paste to run in your Bash shell.

Commands that are to be run on your primary workstation look like
this:

#+begin_run
whoami
hostname
#+end_run

Each code block is intended to be run as a whole (don't copy
individual lines). Click the copy button in the top right corner of any
code block — like the one above — to copy the whole thing to your
clipboard.

Paste the copied command block into your terminal, edit it as
necessary, and then press =Enter= to run it.

You will also sometimes see the /example/ output that a command
prints:

#+begin_stdout
# This is an example of the stdout of the previous command.
# Your output may differ:
ryan
toolbox
#+end_stdout

Pay attention to the style and the title of the box to provide
important context. Commands that are to be run on a different machine,
or in a container, etc. use a distinct style and a title naming where
to run them:

#+attr_shortcode: :style secondary :title Run this inside the container foo:
#+begin_run
whoami
hostname
#+end_run

#+begin_stdout
root
foo
#+end_stdout

**** Config blocks

Temporary shell variables are used to carry common config values
across multiple command blocks. You can copy and paste them just like
you do when running a command, but they are used only for
configuration before running another command:

#+begin_env
COLOR=orange
FOOD="milk chocolate covered raisins"
#+end_env

Subsequent code blocks can reference these temporary variables:

#+begin_run
echo "Favorite color : ${COLOR}"
echo "Favorite food  : ${FOOD}"
#+end_run

#+begin_stdout
Favorite color : orange
Favorite food  : milk chocolate covered raisins
#+end_stdout

**** Edit file blocks

Sometimes it's easiest to edit a file by hand. These blocks invite you
to edit the given file, with your preferred text editor:

#+attr_shortcode: :file /tmp/foo.txt
#+begin_edit
this text goes into /tmp/foo.txt
#+end_edit

** Use Bash 5.1+

#+begin_run
$ bash --version | head -1
#+end_run

#+begin_stdout
GNU bash, version 5.2.26(1)-release
#+end_stdout

The commands written in this book are tested with Bash version 5.2:

*** Bracketed Paste

Since Bash 5.1, *an important feature has been turned on by default:
[[https://en.wikipedia.org/wiki/Bracketed-paste][bracketed paste]]*. This lets you copy and paste multi-line commands,
from this web page, into your terminal, and edit the entire command
directly on the command line, before anything is run. It gives you a
chance to read, /and edit/, the entire command block that you paste,
to be sure its all correct, /before/ you run it. When you're ready,
you press the =Enter= key, and then the whole block is run. To cancel,
press =Ctrl-C=.

 * When you paste a block into Bash, it is automatically highlighted
   in inverse color. This should indicate to you that the command has
   not yet been run.
 * You can edit the entire multiline code block, but you need to be
   careful, *do not press the up or down arrow keys*, because this will
   cancel the command and begin searching your command history
   instead.
 * Use the linear left/right movement keys for [[https://tiswww.cwru.edu/php/chet/readline/rluserman.html][readline]] mode:

   * Left / Right arrow keys to move the cursor one character at a
     time.
   * Ctrl + Left/Right arrow keys, move by words at a time.
   * Ctrl-A moves the cursor to the very beginning of the block.
   * Ctrl-E moves the cursor to the very end of the block.
   * Ctrl-K will "kill" the text after the cursor.
   * To cancel the command before running it, press =Ctrl-C=.
   * To run the reviewed command, press =Enter=.

Before Bash 5.1, unless
you specifically turned this feature on, *commands that you paste
would be run /immediately/*, which is such an insecure anti-feature
for a default setting!

#+attr_shortcode: :style warning
#+begin_notice
If you need to be running an old version of Bash, you should at least
turn on bracketed paste:

#+begin_run
## Only necessary for Bash < 5.1:
echo "bind 'set enable-bracketed-paste on'" >> ~/.bashrc
bind 'set enable-bracketed-paste on'
#+end_run
#+end_notice


* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
