#+hugo_base_dir: ./hugo
#+hugo_section: /
#+hugo_weight: auto
#+hugo_paired_shortcodes: %notice badge button

* book.rymcg.tech
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:END:
This repository contains a collection of books written by EnigmaCurry.

This content is open-source, CC BY 4.0. See [[file:~/git/vendor/enigmacurry/license.org][LICENSE]] for attribution rules.

** Table of contents

The menu bar on the left contains the index of all the books, with the
titles as top level headings. On smaller screens, you may need to
expand this menu using the top left hamburger menu.

At the top left of every page (and just to the right of the sidebar),
there is a button to show the outline of the current page.

** Navigation

This website is presented as a book of books, so you can read
everything from beginning to end. Use your keyboard left/right arrow
keys to flip through the pages. If you are using a touch screen
interface, use the arrow buttons at the top right of the page.

** Search

Use the search box in the left hand menu to search all of the books on
the site.

* Footnotes
* COMMENT Local Variables                          :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
