#+hugo_base_dir: ../hugo
#+hugo_section: /publishing-with-org-mode
#+hugo_weight: auto
#+hugo_paired_shortcodes: %notice %annotate badge button %children %index run stdout edit math mermaid openapi
#+STARTUP: align

* Publishing with org-mode
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :linkTitle Publishing with org-mode
:EXPORT_HUGO_WEIGHT: 900
:EXPORT_HUGO_SLUG: _index
:END:

This book describes how this site is written, in Org-mode, with
ox-hugo, and bits of Literate Programming.

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index

* Dependencies
:PROPERTIES:
:EXPORT_FILE_NAME: dependencies
:EXPORT_HUGO_SLUG: dependencies
:END:

This site is built with:

- [[https://www.gnu.org/software/emacs/][Emacs]]
- [[https://orgmode.org/][Org-mode]]
- [[https://ox-hugo.scripter.co/][Ox-hugo]]
- [[https://gohugo.io][Hugo]] (extended edition)
- GitHub actions (also compatible with Gitea actions)

The GitHub/Gitea actions file includes all its dependencies
declaratively.

To build locally, you must install Emacs (29+), and hugo (v0.120+),
using your package manager, or by downloading directly from their
respective project pages. Please be aware that hugo has two editions:
[[https://gohugo.io/installation/linux/#editions][standard and extended]], and this build requires the extended edition
(TODO: verify this - I had some problems before - but maybe they are
resolved - I am still using the extended edition for now).

Read the [[/linux-workstation/config/emacs-on-fedora/index.html][Linux Workstation chapter for setting up Emacs]].

Please note that your package manager may container an old version of
Hugo that is incompatible with the Relearn theme. You can install the
/latest/ version of Hugo from the [[https://github.com/gohugoio/hugo/releases][Hugo GitHub releases page]].

For example, to download the X86_64 release of hugo =v0.123.8=:

#+begin_run
## Do this if your package manager installs an old incompatible version of Hugo:
HUGO_VERSION=0.123.8
cd ~/Downloads
wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
tar xfvz hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz
sudo install hugo /usr/local/bin/hugo
#+end_run

You will also need to clone the git source of this website to your
workstation:

#+begin_run
git clone https://github.com/EnigmaCurry/org.git 
   ~/git/vendor/enigmacurry/org
#+end_run

* Building locally
:PROPERTIES:
:EXPORT_FILE_NAME: building-locally
:EXPORT_HUGO_SLUG: building-locally
:END:

Change into the directory where you cloned the source:

#+begin_run
cd ~/git/vendor/enigmacurry/org
#+end_run

Run the install method to download the theme:

#+begin_run
## This just downloads/installs the theme:
make install
#+end_run

Build the site:

#+begin_run
## This builds the entire static site into the public/ directory:
make build
#+end_run

Run the development server:

#+begin_run
## This builds the entire site, and then runs the live reload server:
make serve
#+end_run

* Publishing with GitHub pages
:PROPERTIES:
:EXPORT_FILE_NAME: publish-with-github-pages
:EXPORT_HUGO_SLUG: publish-with-github-pages
:END:

This site is automatically published to [[https://pages.github.com][GitHub Pages]] via the included
action file: [[https://github.com/EnigmaCurry/org/blob/ox-hugo/.github/workflows/deploy.yaml][.github/workflows/deploy.yaml]]. You can fork the
repository and enable the action to run on your behalf and publish to
your own site automatically, whenever you run =git push=.

* Publishing with SFTP
:PROPERTIES:
:EXPORT_FILE_NAME: publish-with-sftp
:EXPORT_HUGO_SLUG: publish-with-sftp
:END:

If you don't want to use GitHub pages, you can alternatively publish
to any webserver via SFTP.

To do so, you must install [[https://rclone.org/][Rclone]].

For example, on Fedora:

#+begin_run
## On Fedora atomic, make sure to do this in a toolbox container:
sudo dnf install rclone
#+end_run

Once installed, you need to configure the remote SFTP server you want to publish to:

#+begin_run
rclone config
#+end_run

Follow the prompts to setup your SFTP remote, or you can see the
[[https://rclone.org/sftp/][example SFTP documentation]] for doing this. You must set all of the
following details:

 * The unique name of the remote (eg. =book=)
 * The hostname of the SFTP server (eg. =sftp.example.com=)
 * The SFTP username, password, or SSH key, and whether to use the SSH
   agent (recommended!)

The connection details are saved in your clone config file (eg.
=~/.config/rclone/rclone.conf=)

The included [[https://github.com/EnigmaCurry/org/blob/ox-hugo/Makefile][Makefile]] has a variable at the top called
=PUBLISH_RCLONE_REMOTE= (default =book=). Make sure this is the same
as the name of the rclone remote you configured (edit the Makefile if
it is not).

Once everything is configured, simply run =make publish= to publish
your site to the SFTP remote.

Your webserver document root needs to be configured to use the same
path that the SFTP server is configured for.

If you don't have a webserver or SFTP server, you can use the
following from d.rymcg.tech:

 * [[https://github.com/EnigmaCurry/d.rymcg.tech/tree/master/sftp#readme][SFTP server]]
 * [[https://github.com/EnigmaCurry/d.rymcg.tech/tree/master/nginx#readme][Nginx webserver]]

* Using Org-mode and Emacs
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: org-mode-emacs
:END:

** Using Org-mode and Emacs
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_WEIGHT: 2000
:EXPORT_HUGO_SLUG: _index
:END:

Here are some tips on using Org-mode and Emacs.

*** Read the Org manual

Many of these tips are found in the [[https://orgmode.org/org.html][Org Manual]].

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index
** Navigating Org-mode files
:PROPERTIES:
:EXPORT_FILE_NAME: navigating-org-mode
:EXPORT_HUGO_SLUG: navigating-org-mode
:END:

*** Navigating by search

One of the easiest ways of navigating an Org document, isn't even an
Org feature. Just search for the text you're looking for and jump
right to it.

 * Press =C-s= (or =M-x isearch-forward=)

Of course, you might not always know the exact text (or it might not
be unique enough to take you right there), so its useful to know some
other ways of navigating Org documents.
 
*** Navigating by headers

Another great way to navigate your Org documents is by traversing the
headers. My emacs config sets the default startup visibility to
folded, so you can always get back to a folded state:

 * Press =C-u C-u TAB= (or =M-x org-set-startup-visibility=)

Cycle the visibility of the headers (foldedness):
   
 * Press =TAB= to cycle the folding of the selected header (your
   cursor has to be on a header).
 * Press =C-u TAB= to cycle the folding of the headers in
   the whole buffer (cursor can be anywhere).
 * Press =C-u C-u C-u TAB= (or =M-x org-show-all) to show the entire
   buffer unfolded.
 
If you're in the middle of a paragraph, and want to move to the header
of the current section:

 * Press =s-<up>= (or =C-c C-p= or =M-x org-previous-visible-heading=)
 * Press it again to go to the section before that, etc.

To move to the next section:

 * Press =s-<down>= (or =C-c C-n= or =M-x org-next-visible-heading=)

Moving to the next higher heading is very useful:

 * Press =C-c C-u= (or =M-x outline-up-heading=).

From the parent heading you get to see the outline of the outer
context of what you're currently writing about. From here you can
press =Tab= twice to fold all all the sibling sections and get an
overview.

 * Press =C-c C-u TAB TAB=.

Here are some other header movement commands:

 * =C-c C-f= (=M-x org-forward-heading-same-level=)
 * =C-c C-b= (=M-x org-backward-heading-same-level=)
   
*** Jumping around (org-goto)

You may frequently find yourself needing to jump around in a document,
but don't want to lose your current place.

 * Press =C-c C-j= (or =M-x org-goto=). Mnemonic "jump".
 * Immediately press =Enter= to close the org-goto menu (theres
   advanced searching functions in there, but you ignore that for
   now).

This will save your current place, allowing you to go find the place
you need to temporarily go to.

When you're done, and you want to go back to to where you were:

 * Press =C-c &=. (or =M-x org-mark-ring-goto=).

One mnemonic for =&= is that it is the same syntax for a C pointer
reference.
 
*** Indirect Buffers and Narrow To Subtree

One of the advantages of Org-mode is you can organize lots of
different articles into one big file. This is also a disadvantage when
you are trying to focus on just one of them. It is easy to get lost.

As an example, open the other book named [[https://github.com/EnigmaCurry/org/blob/ox-hugo/books/d.rymcg.tech.org?plain=1][d.rymcg.tech.org]] (found in
this same directory). Let's say we want to focus on the chapter named
=Traefik Proxy=.

 * Press =C-x 4 c=. (or =M-x clone-indirect-buffer-other-window=).

You now have *two buffers* open for the *same* file:
=d.rymcg.tech.org= (the original) and =d.rymcg.tech.org<2>= (the
clone), and you are automatically switched focus to the newly cloned
buffer.

Rename the new buffer to =traefik= so you don't get confused:

 * Press =C-x x r= (or =M-x rename-buffer=).
 * Type the new name: =traefik=.

Now find the chapter you want to focus on:
   
 * Navigate to the chapter heading named =* Traefik Proxy=, make sure
   your cursor is now somewhere on this line.

Narrow the buffer to the selected subtree:

 * Press =C-x n s= (or =M-x org-narrow-to-subtree=).

You have now completed the process of narrowing the content of this
buffer to only the Traefik Proxy article. It is important to know that
the =traefik= buffer is still an indirect clone of the original
=d.rymcg.tech.org= buffer, and they are both simultaneously editing
the same underlying file. But now you know how to focus on a bite
sized peice of a larger file. Go ahead and create more buffers to work
on other parts you frequently need to focus on.

If you need to widen the buffer again:

 * Press =C-x n w= (or =M-x widen=)


** Editing Org-mode files
:PROPERTIES:
:EXPORT_FILE_NAME: editing-org-mode
:EXPORT_HUGO_SLUG: editing-org-mode
:END:

*** Hyperlinks

To add hyperlinks to documents, I find it easiest to type the text
first, and then add the link.

 * Type the link text.
 * Navigate point to the last character of the link text.
 * Press =C-SPC= (Control Spacebar) to mark the position.
 * Navigate point to the first character of the link text.
 * The link text should now be selected.
 * Press =C-c o i= (or =M-x org-insert-link=).
 * Enter the hyperlink URL.
 * Absolute URLs should start with =https://=.
 * Relative URLs can reference the root of the domain with =/=.
 * Just remember, since all links are going through Hugo, links have
   to be in the context of what the web browser can find, not all
   local Org links are valid.
   
* Examples
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: examples
:END:

** Example Org / Hugo content
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SLUG: _index
:END:

This chapter serves as an example of various shortcodes/markup for
[[https://ox-hugo.scripter.co/doc/shortcodes/][Ox-Hugo]] and the [[https://mcshelby.github.io/hugo-theme-relearn/shortcodes/index.html][Hugo Relearn theme]].

This chapter is broken into several sub-chapters to discuss the
various Hugo related features.

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index

** Shaders
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: shaders
:END:

*** Shaders
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SLUG: _index
:END:

The experimental =shader= block embeds live WebGL into a page. These
chapters cover the three ways to use it: inline windows, writing shaders
literately in the block body, and the full-screen takeover mode.

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index

*** Inline windows
:PROPERTIES:
:EXPORT_FILE_NAME: inline-windows
:EXPORT_HUGO_SLUG: inline-windows
:END:

A =shader= block embeds a live WebGL window in the page. Each window has
a single *play/stop* control — stopping rewinds to the start, so play
always begins fresh. Here is the built-in shader, set to autoplay:

#+attr_shortcode: :autoplay true
#+begin_shader
#+end_shader

To present a window stopped on its first frame instead — letting the
reader press play to start it — pass =:autoplay false=:

#+attr_shortcode: :autoplay false
#+begin_shader
#+end_shader

With JavaScript disabled, shader windows are simply not shown and the
page reads normally — the effect is pure progressive enhancement.

*** Sizing
:PROPERTIES:
:EXPORT_FILE_NAME: sizing
:EXPORT_HUGO_SLUG: sizing
:END:

By default a window fills the content width at a clamped height. Size an
individual window with =:width=, =:height=, and/or =:aspect-ratio=. Bare
numbers are pixels; any CSS length or percentage works too.

Fixed =:width= and =:height= (here 320×200):

#+attr_shortcode: :autoplay true :width 320 :height 200
#+begin_shader
#+end_shader

=:width= alone — the height stays the default:

#+attr_shortcode: :autoplay true :width 240
#+begin_shader
#+end_shader

=:height= alone — the width stays full-width:

#+attr_shortcode: :autoplay true :height 120
#+begin_shader
#+end_shader

=:aspect-ratio= on its own is the "fit the default" case: it keeps the
default height and derives the width to match the ratio (never wider than
the content). Here a square:

#+attr_shortcode: :autoplay true :aspect-ratio 1/1
#+begin_shader
#+end_shader

Pair =:aspect-ratio= with a single dimension to derive the other — a
16:9 window 480px wide:

#+attr_shortcode: :autoplay true :width 480 :aspect-ratio 16/9
#+begin_shader
#+end_shader

The same works for literate (custom GLSL) windows — the sizing attributes
are independent of the shader body.

*** Literate shaders
:PROPERTIES:
:EXPORT_FILE_NAME: literate-shaders
:EXPORT_HUGO_SLUG: literate-shaders
:END:

For a literate book, write the fragment shader *in the block itself*. The
body is a Shadertoy-style =mainImage= and the engine compiles and runs it
in the window. The inputs are =iResolution= (vec3), =iTime= (float),
=iAccent= (vec3, the current theme accent) and =iBackground= (vec3, the
theme background — use it as your base color so the shader suits light
and dark palettes). When a block has a body its source is shown alongside
the window by default:

#+attr_shortcode: :autoplay true
#+begin_shader
void mainImage(out vec4 fragColor, in vec2 fragCoord){
  vec2 uv = fragCoord / iResolution.xy;
  float wave = sin(uv.x * 12.0 + iTime)
             * cos(uv.y * 9.0 - iTime * 0.6);
  float v = 0.5 + 0.5 * wave;
  vec3 col = mix(iBackground, iAccent, v);
  fragColor = vec4(col, 1.0);
}
#+end_shader

A GLSL compile error is shown right in the window, so you can iterate on
the shader as you write. Use =:source false= to hide the source box for a
block that has one.

Because =iAccent= follows the site theme, a literate shader recolors with
the palette — try switching themes while one is playing.

*** Full-screen takeover
:PROPERTIES:
:EXPORT_FILE_NAME: takeover
:EXPORT_HUGO_SLUG: takeover
:END:

=:effect takeover= renders full-screen behind the *whole* page, using a
single persistent canvas that survives navigation (only reconfigured,
never recreated, as you move between pages) rather than an inline
window. A small floating play/stop panel appears while a takeover is
active. Pair it with =:hidden= so only the background shows.

An empty takeover block runs the built-in ambient wave. Put a
Shadertoy-style =mainImage= in the block body and *that* shader becomes
the background instead — the engine swaps GLSL programs on navigation,
so different chapters can each drive the same persistent canvas with
their own shader.

This page's background is the Platonic solids demo below: five
[[https://en.wikipedia.org/wiki/Platonic_solid][Platonic solids]] as overlapping projected wireframes, each cycling
through its own set of symmetric orientations at a different period.
Look past the page, not at this spot; then navigate away to another
chapter to see it switch off (the persistent canvas stays alive, just
idle), and back to see it return. The shader also uses two literate
engine features:

- =iAccent= — a live =vec3= uniform carrying the site's current accent
  colour; the tetrahedron uses it so the render tracks the theme.
- =// @slider NAME MIN MAX DEFAULT [STEP]= — a comment-directive the
  engine turns into a =uniform float= plus a slider in the corner
  controls panel (here: =tempo=, drag it to speed the tumble up or
  slow it down).

#+attr_shortcode: :effect takeover :hidden true
#+NAME: platonic-solids-shader
#+begin_shader
// Five Platonic solids as overlapping projected wireframes; each cycles
// through its own set of symmetric orientations at a different period.

const float PI  = 3.14159265359;
const float PHI = 1.618033988749895;

// --- Rotation matrices (right-handed, active) -------------------------------
mat3 rotX(float a){ float c=cos(a), s=sin(a);
  return mat3(1.0,0.0,0.0,  0.0,c,-s,  0.0,s,c); }
mat3 rotY(float a){ float c=cos(a), s=sin(a);
  return mat3(c,0.0,s,  0.0,1.0,0.0,  -s,0.0,c); }
mat3 rotZ(float a){ float c=cos(a), s=sin(a);
  return mat3(c,-s,0.0,  s,c,0.0,  0.0,0.0,1.0); }

// --- Distance from point to line segment ------------------------------------
float segDist(vec2 p, vec2 a, vec2 b){
  vec2 pa = p - a, ba = b - a;
  float h = clamp(dot(pa, ba) / dot(ba, ba), 0.0, 1.0);
  return length(pa - ba * h);
}

// --- Keyframe table (33 poses in one flat index space) ----------------------
// GLSL ES 1.00 has no `vec3[N](...)` array constructor, so the table is a
// cascade of returns instead of a const array. Each solid owns a contiguous
// slice; symRotation() supplies the slice's offset.
vec3 keyframe(int i){
  // Tetrahedron (7 keyframes, offset 0)
  if(i ==  0) return vec3(0.0,      0.0,       0.0);
  if(i ==  1) return vec3(0.31*PI,  0.0,       0.75*PI);
  if(i ==  2) return vec3(0.31*PI,  0.0,       0.25*PI);
  if(i ==  3) return vec3(0.25*PI,  0.0,       0.25*PI);
  if(i ==  4) return vec3(0.0,     -0.25*PI,   0.0);
  if(i ==  5) return vec3(0.0,      0.25*PI,   0.0);
  if(i ==  6) return vec3(0.0,      0.0,       0.25*PI);
  // Cube (5 keyframes, offset 7)
  if(i ==  7) return vec3(0.0,      0.0,       0.0);
  if(i ==  8) return vec3(0.0,      0.3*PI,    0.25*PI);
  if(i ==  9) return vec3(0.0,      0.24*PI,   0.25*PI);
  if(i == 10) return vec3(0.0,      0.125*PI,  0.25*PI);
  if(i == 11) return vec3(0.0,      0.25*PI,   0.0);
  // Octahedron (9 keyframes, offset 12)
  if(i == 12) return vec3(0.0,      0.0,       0.0);
  if(i == 13) return vec3(0.0,      0.5,       0.0);
  if(i == 14) return vec3(0.12,     PI,        0.0);
  if(i == 15) return vec3(0.0,      0.25*PI,   0.25*PI);
  if(i == 16) return vec3(0.0,      0.25*PI,   0.0);
  if(i == 17) return vec3(0.35*PI,  0.25*PI,   0.0);
  if(i == 18) return vec3(0.25*PI,  0.25*PI,   0.0);
  if(i == 19) return vec3(0.5*PI,   0.25*PI,   0.0);
  if(i == 20) return vec3(0.25*PI,  0.0,       0.0);
  // Icosahedron (7 keyframes, offset 21)
  if(i == 21) return vec3(0.0,      0.0,       0.0);
  if(i == 22) return vec3(0.125*PI, 0.0,       0.0);
  if(i == 23) return vec3(0.0,      0.125*PI,  0.0);
  if(i == 24) return vec3(0.0,      0.125*PI,  0.5*PI);
  if(i == 25) return vec3(0.0,      0.25*PI,   0.5*PI);
  if(i == 26) return vec3(0.25*PI,  0.0,       0.0);
  if(i == 27) return vec3(0.5*PI,   0.0,       0.0);
  // Dodecahedron (5 keyframes, offset 28)
  if(i == 28) return vec3(0.0,      0.0,       0.0);
  if(i == 29) return vec3(0.0,      0.12*PI,   0.0);
  if(i == 30) return vec3(0.25*PI,  0.0,       0.0);
  if(i == 31) return vec3(0.5*PI,   PI,        0.24);
  return         vec3(0.5*PI,   0.0,       0.0); // 32
}

// --- Cycle through a solid's keyframes with dwell + smooth transition -------
mat3 symRotation(float t, float period, int offset, int count){
  float phase = t / period;
  int idx = int(mod(floor(phase), float(count)));
  int nxt = int(mod(float(idx + 1), float(count)));
  float f = fract(phase);
  // hold ~12% at each end, ease through the middle
  float e = smoothstep(0.0, 1.0, smoothstep(0.12, 0.88, f));
  vec3 a = mix(keyframe(offset + idx), keyframe(offset + nxt), e);
  return rotX(a.x) * rotY(a.y) * rotZ(a.z);
}

// --- Wireframe glow: sharp core + inner glow + outer bloom + vertex dots ----
vec3 wireRender(float eDist, float vDist, vec3 color){
  float line  = smoothstep(0.006, 0.001, eDist);
  float glow  = exp(-eDist * 160.0) * 0.5;
  float bloom = exp(-eDist * 40.0)  * 0.12;
  float vert  = smoothstep(0.018, 0.006, vDist);
  float vHalo = exp(-vDist * 80.0)  * 0.25;
  return color * (line * 0.7 + glow + bloom) + color * (vert + vHalo);
}

// ============================================================================
// TETRAHEDRON  (4 vertices, 6 edges)
void tetrahedronSolid(vec2 p, mat3 rot, out float eDist, out float vDist){
  const float S = 0.5773502692; // 1/sqrt(3)
  vec2 v0 = (rot * vec3( S,  S,  S)).xy;
  vec2 v1 = (rot * vec3( S, -S, -S)).xy;
  vec2 v2 = (rot * vec3(-S,  S, -S)).xy;
  vec2 v3 = (rot * vec3(-S, -S,  S)).xy;
  eDist =        segDist(p, v0, v1);
  eDist = min(eDist, segDist(p, v0, v2));
  eDist = min(eDist, segDist(p, v0, v3));
  eDist = min(eDist, segDist(p, v1, v2));
  eDist = min(eDist, segDist(p, v1, v3));
  eDist = min(eDist, segDist(p, v2, v3));
  vDist = min(min(length(p - v0), length(p - v1)),
              min(length(p - v2), length(p - v3)));
}

// CUBE  (8 vertices, 12 edges)
void cubeSolid(vec2 p, mat3 rot, out float eDist, out float vDist){
  const float S = 0.5773502692;
  vec2 v[8];
  v[0] = (rot * vec3( S,  S,  S)).xy;
  v[1] = (rot * vec3( S,  S, -S)).xy;
  v[2] = (rot * vec3( S, -S,  S)).xy;
  v[3] = (rot * vec3( S, -S, -S)).xy;
  v[4] = (rot * vec3(-S,  S,  S)).xy;
  v[5] = (rot * vec3(-S,  S, -S)).xy;
  v[6] = (rot * vec3(-S, -S,  S)).xy;
  v[7] = (rot * vec3(-S, -S, -S)).xy;
  eDist =        segDist(p, v[0], v[1]);
  eDist = min(eDist, segDist(p, v[0], v[2]));
  eDist = min(eDist, segDist(p, v[0], v[4]));
  eDist = min(eDist, segDist(p, v[1], v[3]));
  eDist = min(eDist, segDist(p, v[1], v[5]));
  eDist = min(eDist, segDist(p, v[2], v[3]));
  eDist = min(eDist, segDist(p, v[2], v[6]));
  eDist = min(eDist, segDist(p, v[3], v[7]));
  eDist = min(eDist, segDist(p, v[4], v[5]));
  eDist = min(eDist, segDist(p, v[4], v[6]));
  eDist = min(eDist, segDist(p, v[5], v[7]));
  eDist = min(eDist, segDist(p, v[6], v[7]));
  vDist = length(p - v[0]);
  for(int i = 1; i < 8; i++) vDist = min(vDist, length(p - v[i]));
}

// OCTAHEDRON  (6 vertices, 12 edges)
void octahedronSolid(vec2 p, mat3 rot, out float eDist, out float vDist){
  vec2 v[6];
  v[0] = (rot * vec3( 1.0, 0.0, 0.0)).xy;
  v[1] = (rot * vec3(-1.0, 0.0, 0.0)).xy;
  v[2] = (rot * vec3( 0.0, 1.0, 0.0)).xy;
  v[3] = (rot * vec3( 0.0,-1.0, 0.0)).xy;
  v[4] = (rot * vec3( 0.0, 0.0, 1.0)).xy;
  v[5] = (rot * vec3( 0.0, 0.0,-1.0)).xy;
  // every pair except the three antipodal ones (0-1, 2-3, 4-5)
  eDist =        segDist(p, v[0], v[2]);
  eDist = min(eDist, segDist(p, v[0], v[3]));
  eDist = min(eDist, segDist(p, v[0], v[4]));
  eDist = min(eDist, segDist(p, v[0], v[5]));
  eDist = min(eDist, segDist(p, v[1], v[2]));
  eDist = min(eDist, segDist(p, v[1], v[3]));
  eDist = min(eDist, segDist(p, v[1], v[4]));
  eDist = min(eDist, segDist(p, v[1], v[5]));
  eDist = min(eDist, segDist(p, v[2], v[4]));
  eDist = min(eDist, segDist(p, v[2], v[5]));
  eDist = min(eDist, segDist(p, v[3], v[4]));
  eDist = min(eDist, segDist(p, v[3], v[5]));
  vDist = length(p - v[0]);
  for(int i = 1; i < 6; i++) vDist = min(vDist, length(p - v[i]));
}

// ICOSAHEDRON  (12 vertices, 30 edges)
void icosahedronSolid(vec2 p, mat3 rot, out float eDist, out float vDist){
  // Normalized to unit sphere: N = 1/sqrt(1+PHI^2), M = PHI*N
  const float N = 0.5257311121;
  const float M = 0.8506508084;
  vec2 v[12];
  v[0]  = (rot * vec3( 0.0,  N,  M)).xy;
  v[1]  = (rot * vec3( 0.0,  N, -M)).xy;
  v[2]  = (rot * vec3( 0.0, -N,  M)).xy;
  v[3]  = (rot * vec3( 0.0, -N, -M)).xy;
  v[4]  = (rot * vec3(  N,  M, 0.0)).xy;
  v[5]  = (rot * vec3(  N, -M, 0.0)).xy;
  v[6]  = (rot * vec3( -N,  M, 0.0)).xy;
  v[7]  = (rot * vec3( -N, -M, 0.0)).xy;
  v[8]  = (rot * vec3(  M, 0.0,  N)).xy;
  v[9]  = (rot * vec3(  M, 0.0, -N)).xy;
  v[10] = (rot * vec3( -M, 0.0,  N)).xy;
  v[11] = (rot * vec3( -M, 0.0, -N)).xy;
  // v0 neighbors: 2, 4, 6, 8, 10
  eDist =        segDist(p, v[0], v[2]);
  eDist = min(eDist, segDist(p, v[0], v[4]));
  eDist = min(eDist, segDist(p, v[0], v[6]));
  eDist = min(eDist, segDist(p, v[0], v[8]));
  eDist = min(eDist, segDist(p, v[0], v[10]));
  // v1 neighbors: 3, 4, 6, 9, 11
  eDist = min(eDist, segDist(p, v[1], v[3]));
  eDist = min(eDist, segDist(p, v[1], v[4]));
  eDist = min(eDist, segDist(p, v[1], v[6]));
  eDist = min(eDist, segDist(p, v[1], v[9]));
  eDist = min(eDist, segDist(p, v[1], v[11]));
  // v2 neighbors (new): 5, 7, 8, 10
  eDist = min(eDist, segDist(p, v[2], v[5]));
  eDist = min(eDist, segDist(p, v[2], v[7]));
  eDist = min(eDist, segDist(p, v[2], v[8]));
  eDist = min(eDist, segDist(p, v[2], v[10]));
  // v3 neighbors (new): 5, 7, 9, 11
  eDist = min(eDist, segDist(p, v[3], v[5]));
  eDist = min(eDist, segDist(p, v[3], v[7]));
  eDist = min(eDist, segDist(p, v[3], v[9]));
  eDist = min(eDist, segDist(p, v[3], v[11]));
  // v4 neighbors (new): 6, 8, 9
  eDist = min(eDist, segDist(p, v[4], v[6]));
  eDist = min(eDist, segDist(p, v[4], v[8]));
  eDist = min(eDist, segDist(p, v[4], v[9]));
  // v5 neighbors (new): 7, 8, 9
  eDist = min(eDist, segDist(p, v[5], v[7]));
  eDist = min(eDist, segDist(p, v[5], v[8]));
  eDist = min(eDist, segDist(p, v[5], v[9]));
  // v6 neighbors (new): 10, 11
  eDist = min(eDist, segDist(p, v[6], v[10]));
  eDist = min(eDist, segDist(p, v[6], v[11]));
  // v7 neighbors (new): 10, 11
  eDist = min(eDist, segDist(p, v[7], v[10]));
  eDist = min(eDist, segDist(p, v[7], v[11]));
  // remaining: 8-9, 10-11
  eDist = min(eDist, segDist(p, v[8],  v[9]));
  eDist = min(eDist, segDist(p, v[10], v[11]));
  vDist = length(p - v[0]);
  for(int i = 1; i < 12; i++) vDist = min(vDist, length(p - v[i]));
}

// DODECAHEDRON  (20 vertices, 30 edges)
void dodecahedronSolid(vec2 p, mat3 rot, out float eDist, out float vDist){
  // all vertices at distance sqrt(3); normalize by 1/sqrt(3)
  const float S = 0.5773502692; // 1/sqrt(3)
  const float A = 0.3568220898; // (1/PHI)/sqrt(3)
  const float B = 0.9341723590; //   PHI /sqrt(3)
  vec2 v[20];
  // Cube-type (+-1, +-1, +-1)/sqrt(3)
  v[0]  = (rot * vec3( S,  S,  S)).xy;
  v[1]  = (rot * vec3( S,  S, -S)).xy;
  v[2]  = (rot * vec3( S, -S,  S)).xy;
  v[3]  = (rot * vec3( S, -S, -S)).xy;
  v[4]  = (rot * vec3(-S,  S,  S)).xy;
  v[5]  = (rot * vec3(-S,  S, -S)).xy;
  v[6]  = (rot * vec3(-S, -S,  S)).xy;
  v[7]  = (rot * vec3(-S, -S, -S)).xy;
  // (0, +-PHI, +-1/PHI)/sqrt(3)
  v[8]  = (rot * vec3( 0.0,  B,  A)).xy;
  v[9]  = (rot * vec3( 0.0,  B, -A)).xy;
  v[10] = (rot * vec3( 0.0, -B,  A)).xy;
  v[11] = (rot * vec3( 0.0, -B, -A)).xy;
  // (+-1/PHI, 0, +-PHI)/sqrt(3)
  v[12] = (rot * vec3(  A, 0.0,  B)).xy;
  v[13] = (rot * vec3(  A, 0.0, -B)).xy;
  v[14] = (rot * vec3( -A, 0.0,  B)).xy;
  v[15] = (rot * vec3( -A, 0.0, -B)).xy;
  // (+-PHI, +-1/PHI, 0)/sqrt(3)
  v[16] = (rot * vec3(  B,  A, 0.0)).xy;
  v[17] = (rot * vec3(  B, -A, 0.0)).xy;
  v[18] = (rot * vec3( -B,  A, 0.0)).xy;
  v[19] = (rot * vec3( -B, -A, 0.0)).xy;
  // 24 cube-to-rectangle edges
  eDist =        segDist(p, v[0], v[8]);
  eDist = min(eDist, segDist(p, v[0], v[12]));
  eDist = min(eDist, segDist(p, v[0], v[16]));
  eDist = min(eDist, segDist(p, v[1], v[9]));
  eDist = min(eDist, segDist(p, v[1], v[13]));
  eDist = min(eDist, segDist(p, v[1], v[16]));
  eDist = min(eDist, segDist(p, v[2], v[10]));
  eDist = min(eDist, segDist(p, v[2], v[12]));
  eDist = min(eDist, segDist(p, v[2], v[17]));
  eDist = min(eDist, segDist(p, v[3], v[11]));
  eDist = min(eDist, segDist(p, v[3], v[13]));
  eDist = min(eDist, segDist(p, v[3], v[17]));
  eDist = min(eDist, segDist(p, v[4], v[8]));
  eDist = min(eDist, segDist(p, v[4], v[14]));
  eDist = min(eDist, segDist(p, v[4], v[18]));
  eDist = min(eDist, segDist(p, v[5], v[9]));
  eDist = min(eDist, segDist(p, v[5], v[15]));
  eDist = min(eDist, segDist(p, v[5], v[18]));
  eDist = min(eDist, segDist(p, v[6], v[10]));
  eDist = min(eDist, segDist(p, v[6], v[14]));
  eDist = min(eDist, segDist(p, v[6], v[19]));
  eDist = min(eDist, segDist(p, v[7], v[11]));
  eDist = min(eDist, segDist(p, v[7], v[15]));
  eDist = min(eDist, segDist(p, v[7], v[19]));
  // 6 rectangle-to-rectangle edges
  eDist = min(eDist, segDist(p, v[8],  v[9]));
  eDist = min(eDist, segDist(p, v[10], v[11]));
  eDist = min(eDist, segDist(p, v[12], v[14]));
  eDist = min(eDist, segDist(p, v[13], v[15]));
  eDist = min(eDist, segDist(p, v[16], v[17]));
  eDist = min(eDist, segDist(p, v[18], v[19]));
  vDist = length(p - v[0]);
  for(int i = 1; i < 20; i++) vDist = min(vDist, length(p - v[i]));
}

// controls-panel slider scales iTime — drag slower to watch a single tumble,
// faster to hear the five periods beat against each other
// @slider tempo 0.1 3.0 1.0 0.05
uniform float tempo;

void mainImage( out vec4 fragColor, in vec2 fragCoord )
{
  // Recenter and normalize to short-edge units so the layout is aspect-ratio
  // invariant: (0,0) is the middle of the canvas, +/-0.5 is a unit sphere edge.
  vec2 uv = (fragCoord - 0.5 * iResolution.xy) / min(iResolution.x, iResolution.y);

  float t = iTime * 0.5 * tempo;

  // Unit-sphere solids at ~40% of screen height (0.38 leaves a small margin).
  vec2 p = uv / 0.38;

  // Each solid cycles through its own set of pleasing symmetric orientations
  // at a different period, so the overlapping contours keep shifting.
  mat3 rTetra = symRotation(t, 3.5,  0, 7); // tetrahedron: 7 keyframes
  mat3 rCube  = symRotation(t, 4.0,  7, 5); // cube:        5 keyframes
  mat3 rOcta  = symRotation(t, 2.8, 12, 9); // octahedron:  9 keyframes
  mat3 rIcosa = symRotation(t, 3.2, 21, 7); // icosahedron: 7 keyframes
  mat3 rDodec = symRotation(t, 5.0, 28, 5); // dodecahedron:5 keyframes

  // Edge + vertex distances per pixel, for each solid.
  float eT, vT, eC, vC, eO, vO, eI, vI, eD, vD;
  tetrahedronSolid (p, rTetra, eT, vT);
  cubeSolid        (p, rCube,  eC, vC);
  octahedronSolid  (p, rOcta,  eO, vO);
  icosahedronSolid (p, rIcosa, eI, vI);
  dodecahedronSolid(p, rDodec, eD, vD);

  // Wire colors: iAccent tracks the site's palette; two fixed complementary
  // hues fill the rest so all five solids stay distinguishable on any theme.
  vec3 cTetra = iAccent;
  vec3 cCube  = vec3(0.35, 0.75, 1.00); // cool blue
  vec3 cOcta  = vec3(1.00, 0.35, 0.55); // warm magenta
  vec3 cIcosa = mix(iAccent, cOcta, 0.5);
  vec3 cDodec = mix(cCube,   cOcta, 0.5);

  // Composite wireframes (additive). The two most complex solids are dimmed
  // slightly so their 30 edges don't wash out the tetrahedron and cube.
  vec3 col = vec3(0.0);
  col += wireRender(eT, vT, cTetra);
  col += wireRender(eC, vC, cCube);
  col += wireRender(eO, vO, cOcta);
  col += wireRender(eI, vI, cIcosa) * 0.7;
  col += wireRender(eD, vD, cDodec) * 0.7;

  // Subtle vignette so the corners fall off toward the frame.
  float vig = 1.0 - dot(uv, uv) * 0.5;
  col *= max(vig, 0.0);

  // Scanlines — same trick the built-in ambient shader uses.
  float scan = 0.92 + 0.08 * sin(fragCoord.y * 2.5);
  col *= scan;

  fragColor = vec4(col, 1.0);
}
#+end_shader

** Example Org Blocks
:PROPERTIES:
:EXPORT_FILE_NAME: org-blocks
:EXPORT_HUGO_SLUG: org-blocks
:END:

A couple examples [[https://ox-hugo.scripter.co/doc/org-special-blocks/][ripped from the ox-hugo docs]].

*** Asides

This is a normal paragraph.

#+begin_aside
This is an aside note, which should wrap and stay close to the right hand side of the page. It is used to call out things in an editorial voice.
#+end_aside

This is another normal paragraph.

*** Markers

This paragraph has some
#+begin_mark
highlighted words
#+end_mark
in it.

*** Details

This section shows some hidden details:

#+begin_details
This content is hidden by default.

#+begin_aside
It can contain any
#+begin_mark
additional markup
#+end_mark
you want.
#+end_aside

#+end_details

*** Org-Babel

Source code blocks can be written and evaluated with org-babel:

#+begin_src rust :exports true :wrap stdout :linenos true
  //Rust code
  println!("Hello from Rust!");
#+end_src

#+RESULTS:
#+begin_stdout
Hello from Rust!
#+end_stdout

#+begin_src python :results output :exports true :wrap stdout :linenos true
  #Python code:
  print("hello from python.")
#+end_src

#+RESULTS:
#+begin_stdout
hello from python.
#+end_stdout

#+attr_shortcode: :style primary :title Info
#+begin_notice
With =:exports true= set, code blocks are to be evaluated by hand with
=C-c C-c= (so if you change the code, you must also remember to
re-evaluate the results). It would be nice to use =:exports both= and
have ox-hugo evaluate blocks automatically on export, but I have not
been able to get this to work correctly.
#+end_notice

** Diffs
:PROPERTIES:
:EXPORT_FILE_NAME: diffs
:EXPORT_HUGO_SLUG: diffs
:END:

When one block is an evolution of another, you don't have to paste the
code twice and hand-maintain a changeset. Give each block a unique
=#+NAME:= and add a =#+begin_diff= block that references them; on export
the build replaces it with a box that toggles between a GitHub-style diff
and the full source of the evolved block. Both views are syntax-highlighted
and line-numbered; in the diff, added lines are blocked out in green and
removed lines in red. Any named block works as a reference — =src=,
=example=, or a special block like =shader= — and the two may live in
different subtrees of the same file.

#+begin_src org
,#+NAME: greet-v1
,#+begin_src sh
#!/bin/sh
echo "starting up"
echo "hello"
echo "done"
,#+end_src

,#+NAME: greet-v2
,#+begin_src sh
#!/bin/sh
echo "starting up"
name="world"
echo "hello, $name"
echo "done"
,#+end_src

,#+attr_diff: :from greet-v1 :to greet-v2
,#+begin_diff
,#+end_diff
#+end_src

=#+attr_diff= takes =:from= and =:to= (the two block names) plus a few
optional settings:

- =:context N= — unchanged lines of context around each change (default
  3; use a large value to show the whole block as one changeset).
- =:view diff|source= — which view renders by default (default =diff=).
  This is also the static view shown with JavaScript disabled.
- =:lang LANG= — override the language used to highlight the source view
  (otherwise inferred from the =:to= block; =shader= blocks use =glsl=).

The header reads =Diff: from → to= or =Source: to= to match the view, and
a button in the top-right toggles between them (it folds away when
JavaScript is off, leaving the static =:view=). The build *fails loudly*
if either name is missing or cannot be resolved, so a typo never silently
ships an empty diff. The example above renders:

#+NAME: greet-v1
#+begin_src sh
#!/bin/sh
echo "starting up"
echo "hello"
echo "done"
#+end_src

#+NAME: greet-v2
#+begin_src sh
#!/bin/sh
echo "starting up"
name="world"
echo "hello, $name"
echo "done"
#+end_src

#+attr_diff: :from greet-v1 :to greet-v2
#+begin_diff
#+end_diff

The same two blocks can be referenced again — a named block is not
consumed by a diff. Here is the very same pair with =:view source=, so the
box opens on the evolved source instead of the changeset:

#+attr_diff: :from greet-v1 :to greet-v2 :view source
#+begin_diff
#+end_diff

By default the diff shows only three lines of context around each change,
so a longer file whose edits are far apart renders as separate *hunks*
with the unchanged stretch between them collapsed behind a =@@ … @@=
header. This pair edits a line near the top and another near the bottom:

#+NAME: srv-v1
#+begin_src sh
#!/bin/sh
# greeting service v1
greeting="hello"

main() {
  name="$1"
  echo "$greeting, $name"
  log "$name"
}

log() {
  printf '%s\n' "$1" >> guests.txt
}

main "$@"
#+end_src

#+NAME: srv-v2
#+begin_src sh
#!/bin/sh
# greeting service v2
greeting="hi"

main() {
  name="$1"
  echo "$greeting, $name"
  log "$name"
}

log() {
  printf '%s\n' "$1" >> visitors.log
}

main "$@"
#+end_src

#+attr_diff: :from srv-v1 :to srv-v2
#+begin_diff
#+end_diff

To fill the gap and show the whole file as one changeset, pass a =:context=
at least as large as the file — exactly what the whirlpool note below does
with =:context 99=.

You don't always need two named blocks. Reference a *single* block with
=:from= (or =:to=) and write the change directly in the diff block's body;
that body becomes the other side of the diff. This is handy for a one-off
edit you don't want to give its own named block. =:label= names the inline
side (default =edited=). For example, against =greet-v1= from above:

#+begin_src org
,#+attr_diff: :from greet-v1 :label timestamped
,#+begin_diff
#!/bin/sh
echo "starting up"
echo "$(date): hello"
echo "done"
,#+end_diff
#+end_src

which renders:

#+attr_diff: :from greet-v1 :label timestamped
#+begin_diff
#!/bin/sh
echo "starting up"
echo "$(date): hello"
echo "done"
#+end_diff

With =:from= the body is the new (right-hand) side; with =:to= it is the
original instead. The same =:context=, =:view=, and =:lang= settings apply.

A =#+begin_shader= block can carry the same =#+attr_diff: :from NAME= line:
the shader still runs live, but its source box becomes a diffbox against
=NAME=. The shader body is written once — run *and* diffed from a single
block — so there is no duplicated copy to keep in sync. The
[[/shaders/whirlpool/first-whirlpool/][whirlpool note]] does exactly this.

#+attr_shortcode: :style primary :title Info
#+begin_notice
The =diff= block is DRY: only the named blocks hold the source, so the
changeset can never drift from the code it describes. See it used in the
[[/shaders/whirlpool/first-whirlpool/][whirlpool shader note]], which shows the whole shader as a changeset
from the step-function shader on the previous page.
#+end_notice

#+attr_shortcode: :style warning :title Caveat
#+begin_notice
The diff and source are handed to the renderer verbatim, so the referenced
code must not contain a literal Hugo shortcode opener — a ={{= immediately
followed by =<= (or by =%=). Ordinary ={{= braces on their own are fine.
#+end_notice


** Example Shortcodes
:PROPERTIES:
:EXPORT_FILE_NAME: shortcodes
:EXPORT_HUGO_SLUG: shortcodes
:END:
Here are some example usage of the [[https://mcshelby.github.io/hugo-theme-relearn/shortcodes/index.html][shortcodes provided by the Hugo
Relearn theme]]. Shortcodes are a native feature of Hugo and Hugo
themes. For use with Ox-Hugo, you need to set the
=#+hugo_paired_shortcodes= (For examples, see [[https://ox-hugo.scripter.co/doc/shortcodes/#hugo-paired-shortcodes][Ox-hugo docs]] or the top
of this source file).

You can only use the icon names from the [[https://fontawesome.com/v6/search?o=r&m=free]["free" set provided by
fontawesome]].

*** Badges

#+attr_shortcode: :icon check :style green
#+begin_badge
1.0.0
#+end_badge

#+attr_shortcode: :icon star :style orange
#+begin_badge
99,999
#+end_badge

#+attr_shortcode: :icon phone :style primary
#+begin_badge
867-5309
#+end_badge

#+attr_shortcode: :icon envelope :title Email :style transparent
#+begin_badge
me@example.com
#+end_badge

#+attr_shortcode: :icon book :title Docs
#+begin_badge
https://book.rymcg.tech
#+end_badge

#+attr_shortcode: :icon dumpster-fire :style red
#+begin_badge
Dumpster Fire
#+end_badge

*** Buttons

#+attr_shortcode: :icon code-branch :style primary :href https://github.com/EnigmaCurry/d.rymcg.tech
#+begin_button
d.rymcg.tech
#+end_button

#+attr_shortcode: :icon download :style green :href https://github.com/EnigmaCurry/d.rymcg.tech
#+begin_button
d.rymcg.tech
#+end_button

#+attr_shortcode: :icon door-closed :style red
#+begin_button
Cancel
#+end_button

*** Math

Math with [[https://www.mathjax.org/][MathJax]]:

#+attr_shortcode: :align center
#+begin_math
$$\left( \sum_{k=1}^n a_k b_k \right)^2 \leq \left( \sum_{k=1}^n a_k^2 \right) \left( \sum_{k=1}^n b_k^2 \right)$$
#+end_math

*** Flowcharts

#+begin_mermaid
---
title: Example Diagram
---
graph LR;
    A[Hard edge] -->|Link text| B(Round edge)
    B --> C{<strong>Decision</strong>}
    C -->|One| D[Result one]
    C -->|Two| E[Result two]
#+end_mermaid

*** Notices

#+attr_shortcode:  :style grey :title Notice
#+begin_notice
This is a generic notice.
#+end_notice

#+attr_shortcode:  :style orange :icon bug
#+begin_notice
This is a bug notice.
#+end_notice

#+attr_shortcode:  :style info
#+begin_notice
This is an information box. 
#+end_notice

#+attr_shortcode:  :style tip
#+begin_notice
This is a tip or pointer. 
#+end_notice

#+attr_shortcode:  :style warning :icon skull-crossbones
#+begin_notice
This is a warning.
#+end_notice

*** OpenAPI

Visualize your API with swagger spec.

#+attr_shortcode: :src /openapi/petstore.json
#+begin_openapi

#+end_openapi

** Examples of Subchapters
*** Deeply ...
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: deeply
:END:

**** Example of a deeply ...
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SLUG: _index
:END:

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index

**** Nested ...
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: nested
:END:
***** Nested ...
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SLUG: _index
:END:

#+attr_shortcode: :depth 999
#+begin_index
index
#+end_index

***** Sub-chapters
:PROPERTIES:
:EXPORT_HUGO_SECTION_FRAG: subchapters
:END:

****** Sub-chapter 1
:PROPERTIES:
:EXPORT_FILE_NAME: subchapter1
:EXPORT_HUGO_SLUG: subchapter1
:END:

This is a deeply nested sub-chapter. Take a look at the Org source. It
requires that you create several headings and create the index in a
sub-heading of the same name. It is a strangeness about ox-hugo that
this is required. If you make a strictly hierarchical outline, the
content will be duplicated, however the structure we're using hides
the nested content on the index pages, leaving it for the nested page
only.

****** Sub-chapter 2
:PROPERTIES:
:EXPORT_FILE_NAME: subchapter2
:EXPORT_HUGO_SLUG: subchapter2
:END:

This is another deeply nested sub-chapter as a sibling of the one before it.

****** Sub-chapter 3
:PROPERTIES:
:EXPORT_FILE_NAME: subchapter3
:EXPORT_HUGO_SLUG: subchapter3
:END:

This is another deeply nested sub-chapter as a sibling of the one before it.

