#+hugo_base_dir: ../hugo
#+hugo_section: /notes/guix
#+hugo_weight: auto
#+hugo_paired_shortcodes: %notice badge button %children %index run stdout edit math mermaid openapi result expand
#+startup: align
* Guix
:PROPERTIES:
:EXPORT_FILE_NAME: _index
:EXPORT_HUGO_SLUG: _index
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :alwaysopen false
:END:
#+begin_comment
This is the default index for 2025-01-08 and it is boilerplate.
Don't write anything here.
This section will be overwriten by the template
(enigmacurry/org/notes/_template/note.o.txt).
Write your new top level sections below this one.
#+end_comment
#+attr_shortcode: :depth 999 :sort title
#+begin_index
index
#+end_index

* Guix (Debian) Server
:PROPERTIES:
:EXPORT_FILE_NAME: 000000-guix-server-(debian)
:EXPORT_HUGO_SLUG: guix-server-(debian)
:EXPORT_HUGO_WEIGHT: auto
:header-args: :async :results output :exports true :wrap stdout :dir /ssh:guixvm:tmp/guix
:END:

This org-babel session uses TRAMP to manage a freshly installed remote
Debian server (named =guixvm=) over SSH. For more infomration about
this style of administration see [[https://howardism.org/Technical/Emacs/literate-devops.html][Howard Abrams' Literate DevOps]].

** Configure SSH access

First of all, you need the =guixvm= host configured in your
workstation's =~/.ssh/config=:

#+begin_example
## In ~/.ssh/config
Host guixvm
     Hostname 10.10.1.2
     User ryan
     ControlMaster auto
     ControlPersist yes
     ControlPath /tmp/ssh-%u-%r@%h:%p
     UserKnownHostsFile ~/.ssh/known_hosts
#+end_example

** Install Guix

On the remote host, install guix and have it pull updates. The next
block will run asynchronously and will take quite a long while to
complete (=guix pull= is super slow):

#+begin_src shell
  sudo apt update
  sudo apt install -y guix colorized-logs
  time guix pull 2>&1 | ansi2txt
#+end_src

Configure the bourne shell profile for guix:

#+begin_src shell
cat <<'EOF' >> ~/.profile
    
export GUIX_PROFILE=~/.guix-profile
. ${GUIX_PROFILE}/etc/profile
  
EOF
#+end_src

#+RESULTS:
#+begin_stdout
#+end_stdout

** Install Emacs

Install some packages:

#+begin_src shell
  # ansi2txt filters out fancy text so it doesnt give org-babel grief:
  guix package -i emacs | ansi2txt
#+end_src

Emacs is now installed in the user guix-profile, and it is a shell script that points to the Emacs binary in the root guix store (=/gnu/store/..../bin/.emacs-28.2-real=):

#+begin_src shell :results output :exports true :wrap stdout :linenos true
cat ~/.guix-profile/bin/emacs
#+end_src

#+RESULTS:
#+begin_stdout
#!/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash
export XDG_DATA_DIRS="/gnu/store/jkngmzz91vzd47d9lw777d9ihcw8aqpf-shared-mime-info-1.15/share:/gnu/store/2jj2mxn6wfrcw7i85nywk71mmqbnhzps-glib-2.70.2/share:/gnu/store/y21hxgpcl7q2nvr8p7blhvx64xaw3rs8-gtk+-3.24.30/share:/gnu/store/rfggqmqzcpz4wwjhj2y0bcfmqx8c8i93-emacs-28.2/share${XDG_DATA_DIRS:+:}$XDG_DATA_DIRS"
export GTK_PATH="/gnu/store/y21hxgpcl7q2nvr8p7blhvx64xaw3rs8-gtk+-3.24.30/lib/gtk-3.0${GTK_PATH:+:}$GTK_PATH"
export PATH="$PATH${PATH:+:}/gnu/store/0c1yfbxyv877mlgychfgvmk5ha2jqh52-gzip-1.10/bin:/gnu/store/8fpk2cja3f07xls48jfnpgrzrljpqivr-coreutils-8.32/bin"
export EMACSLOADPATH="$EMACSLOADPATH${EMACSLOADPATH:+:}/gnu/store/rfggqmqzcpz4wwjhj2y0bcfmqx8c8i93-emacs-28.2/share/emacs/28.2/lisp"
exec -a "$0" "/gnu/store/rfggqmqzcpz4wwjhj2y0bcfmqx8c8i93-emacs-28.2/bin/.emacs-28.2-real" "$@"
#+end_stdout

#+begin_src shell :results output :exports true :wrap stdout :linenos true
  source ~/.profile
  emacs --version 2>&1
#+end_src

#+RESULTS:
#+begin_stdout
/gnu/store/4y5m9lb8k3qkb1y9m02sw9w9a6hacd16-bash-minimal-5.1.8/bin/bash: warning: setlocale: LC_ALL: cannot change locale (C.utf8)
GNU Emacs 28.2
Copyright (C) 2022 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.
#+end_stdout

** List installed packages

#+begin_src shell :results output :exports true :wrap stdout :linenos true
guix package --list-installed
#+end_src

#+RESULTS:
#+begin_stdout
emacs	28.2	out	/gnu/store/rfggqmqzcpz4wwjhj2y0bcfmqx8c8i93-emacs-28.2
#+end_stdout


** Rollback changes

You can see the transaction that introduced the changeset for the Emacs package:

#+begin_src shell :results output :exports true :wrap stdout :linenos true
guix package --list-generations | ansi2txt
#+end_src

#+RESULTS:
#+begin_stdout
Generation 1	Jan 09 2025 21:59:32	(current)
  emacs	28.2	out	/gnu/store/rfggqmqzcpz4wwjhj2y0bcfmqx8c8i93-emacs-28.2

#+end_stdout

You could remove the package, going forward, but you can also just
rollback the change, going backward:

#+begin_src shell
guix package --roll-back
#+end_src

#+RESULTS:
#+begin_stdout
switched from generation 1 to 0
#+end_stdout
 
This step returns very quickly, and now Emacs is no longer installed.

The generation (id =1=) is still there though, so you can switch back again:

#+begin_src shell
guix package -S 1
#+end_src

#+RESULTS:
#+begin_stdout
switched from generation 0 to 1
#+end_stdout

Now we have quickly switched back to the generation that installed
Emacs again.

** Read the manual

Read the guix manual for more information. Start with the [[https://guix.gnu.org/manual/en/html_node/Getting-Started.html][Getting
Started]] guide.
